### ISSUE TITLE
gulp error "Cannot read properties of undefined (reading 'Error')"

### ISSUE THREAD

**Issue by olets** [iby/twig-js-markdown#3]
Adding a `{% markdown %}...{% endmarkdown %}` gives me this error:

```
Message:
    Cannot read properties of undefined (reading 'Error')
Details:
    domainEmitter: [object Object]
    domainThrown: false
```

with either

```js
.pipe(twig({
  extend: function(Twig) {
    twigMarkdown(Twig)
  }}))
```

or 

```js
.pipe(twig({ extend: twigMarkdown }))
```
